# Generated by Django 3.2.3 on 2021-06-23 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='city')),
                ('birth_date', models.DateTimeField(blank=True, null=True, verbose_name='Birth date')),
                ('bio', models.CharField(blank=True, max_length=120, verbose_name='About me')),
                ('image', models.ImageField(upload_to='profile_pictures', verbose_name='Profile image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
